//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashOrderDetail
    {
        public int CashOrderItemId { get; set; }
        public int CashOrderId { get; set; }
        public int ProductNumber { get; set; }
        public int SupplierNumber { get; set; }
        public int CustodianNumber { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public decimal OrderItemTotal { get; set; }
    }
}
