//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharliesTransportCourierFeeReference
    {
        public int DeliveryCostID { get; set; }
        public int PostalCodeRangeStart { get; set; }
        public int PostalCodeRangeEnd { get; set; }
        public Nullable<decimal> WeightStartRange { get; set; }
        public Nullable<decimal> WeightEndRange { get; set; }
        public string MainCentre { get; set; }
        public decimal DeliveryFee { get; set; }
    }
}
