//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourierCustodianDistance
    {
        public int CourierNumber { get; set; }
        public int CustodianNumber { get; set; }
        public Nullable<decimal> Distance { get; set; }
    
        public virtual Courier Courier { get; set; }
        public virtual Custodian Custodian { get; set; }
    }
}
