//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourierLocation
    {
        public int CourierNumber { get; set; }
        public int LocationNumberOrigin { get; set; }
        public int LocationNumberDestination { get; set; }
        public decimal CourierFee { get; set; }
    
        public virtual Courier Courier { get; set; }
        public virtual Location Location { get; set; }
        public virtual Location Location1 { get; set; }
    }
}
