//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalWebsite
    {
        public int LinkId { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string Description { get; set; }
        public int Department { get; set; }
        public bool Activated { get; set; }
    }
}
