//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalWebsitePicture
    {
        public int PictureNumber { get; set; }
        public int WebsiteNumber { get; set; }
        public byte[] Picture { get; set; }
        public string Annotation { get; set; }
        public string Dimensions { get; set; }
        public string PictureMimeType { get; set; }
    }
}
