//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreeMarketOwner
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string TelephoneNumber { get; set; }
        public string CellphoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string BankingDetailsBankName { get; set; }
        public string BankingDetailsBranchName { get; set; }
        public string BankingDetailsBranchCode { get; set; }
        public string BankingDetailsAccountNumber { get; set; }
        public string BankingDetailsAccountType { get; set; }
        public string BankAccountType { get; set; }
        public string ProofOfPaymentEmail { get; set; }
    }
}
