//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location()
        {
            this.CourierLocations = new HashSet<CourierLocation>();
            this.CourierLocations1 = new HashSet<CourierLocation>();
            this.Custodians = new HashSet<Custodian>();
        }
    
        public int LocationNumber { get; set; }
        public string PostalCode { get; set; }
        public string LocationName { get; set; }
        public Nullable<decimal> Lattitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string FarmName { get; set; }
        public string StreetAddress { get; set; }
        public string TownName { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourierLocation> CourierLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourierLocation> CourierLocations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Custodian> Custodians { get; set; }
    }
}
