//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderHeader()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDatePlaced { get; set; }
        public Nullable<System.DateTime> OrderDateClosed { get; set; }
        public string CustomerNumber { get; set; }
        public string OrderStatus { get; set; }
        public string DeliveryType { get; set; }
        public bool PaymentReceived { get; set; }
        public string DeliveryAddress { get; set; }
        public string DeliveryAddressLine1 { get; set; }
        public string DeliveryAddressLine2 { get; set; }
        public string DeliveryAddressLine3 { get; set; }
        public string DeliveryAddressLine4 { get; set; }
        public string DeliveryAddressSuburb { get; set; }
        public string DeliveryAddressCity { get; set; }
        public string DeliveryAddressPostalCode { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> DeliveryDateAgreed { get; set; }
        public Nullable<decimal> TaxTotal { get; set; }
        public Nullable<decimal> ShippingTotal { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public decimal TotalOrderValue { get; set; }
        public Nullable<int> CourierNumber { get; set; }
        public Nullable<System.DateTime> DateDispatched { get; set; }
        public Nullable<System.DateTime> DateRefunded { get; set; }
        public string TrackingCodes { get; set; }
        public Nullable<int> PaymentOption { get; set; }
        public Nullable<bool> InvoiceSent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
