//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderHeader()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDatePlaced { get; set; }
        public Nullable<System.DateTime> OrderDateClosed { get; set; }
        public string CustomerNumber { get; set; }
        public string OrderStatus { get; set; }
        public string CustomerOverallSatisfactionRating { get; set; }
        public bool PaymentReceived { get; set; }
        public Nullable<decimal> TaxTotal { get; set; }
        public Nullable<decimal> ShippingTotal { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public decimal TotalOrderValue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
