//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentGatewayParameter
    {
        public int PaymentGatewayNumber { get; set; }
        public string PaymentGatewayName { get; set; }
        public Nullable<decimal> PaymentGatewayID { get; set; }
        public string TransactionRequestUrl { get; set; }
        public string Return_Url { get; set; }
        public string Notify_Url { get; set; }
        public string RedirectToSecurePayment_Url { get; set; }
    }
}
