//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSupplier
    {
        public int ProductNumber { get; set; }
        public int SupplierNumber { get; set; }
        public decimal PricePerUnit { get; set; }
        public Nullable<decimal> SpecialPricePerUnit { get; set; }
        public Nullable<decimal> RetailPricePerUnit { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
