//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Special
    {
        public int SpecialID { get; set; }
        public string SpecialPostalCodeRangeStart { get; set; }
        public string SpecialPostalCodeRangeEnd { get; set; }
        public decimal DeliveryFee { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    }
}
