//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Support
    {
        public int SupportID { get; set; }
        public string MainContactName { get; set; }
        public string Cellphone { get; set; }
        public string Landline { get; set; }
        public string Email { get; set; }
        public string OrdersEmail { get; set; }
        public string StreetAddress { get; set; }
        public string TownName { get; set; }
        public string PostalCode { get; set; }
        public string Province { get; set; }
    }
}
